(()=>{const $=s=>document.querySelector(s),gallery=$('#gallery');const KEY='ggrid.theme-lab.enabled.v1';let themes=[],docs=new Map(),enabled=new Set(),current=0;
const fallback=['classic','mine','space-station','ancient-temple','ice-cavern','cybergrid','pirate-ship'];
function markup(t){
 const preview=t.preview?.markup;
 if(preview!=null)return preview.replaceAll('{{cells25}}',Array.from({length:25},(_,i)=>'<i class="cell c'+i+'"></i>').join(''));
 return '<div class="board">'+Array.from({length:16},()=>'<i class="cell"></i>').join('')+'<i class="piece ball"></i><i class="piece brick"></i><i class="piece glue1"></i><i class="piece glue2"></i><i class="piece wall"></i><i class="exit"></i></div>';
}
function paint(el,t){el.dataset.scene=t.scene?.type||'';const c=t.colors||{};for(const [k,v] of Object.entries({wrap:c.wrap||c.background,board:c.board,c1:c.cell1||c.board,c2:c.cell2||c.background,accent:c.accent||'#e3b05b',ball1:c.ball1,ball2:c.ball2,ball3:c.ball3,b1:c.brick1,b2:c.brick2,be:c.brickEdge,w1:c.wall1,w2:c.wall2}))if(v)el.style.setProperty('--'+k,v);el.innerHTML=markup(t)}
let audioCtx=null;function soundDemo(t){const A=window.AudioContext||window.webkitAudioContext;if(!A)return;audioCtx=audioCtx||new A();if(audioCtx.state==='suspended')audioCtx.resume();const c=audioCtx,now=c.currentTime,p=t.audio?.profile||'classic';const presets={haunted:[[220,.6,'sine'],[330,.9,'sine'],[660,.18,'triangle']],city:[[110,.18,'sawtooth'],[165,.12,'square'],[440,.09,'square']],orbital:[[70,.7,'sawtooth'],[980,.12,'sine'],[1470,.16,'sine']],abyss:[[55,.9,'sine'],[110,.7,'sine'],[620,.25,'sine']],clockwork:[[92,.18,'triangle'],[184,.12,'square'],[740,.55,'sine'],[1110,.75,'sine']],neon:[[48,.5,'sawtooth'],[96,.35,'sine'],[420,.1,'square'],[840,.25,'sine']]},seq=presets[p]||[[180,.12,'triangle'],[360,.12,'sine']];seq.forEach((q,i)=>{const o=c.createOscillator(),g=c.createGain(),t0=now+i*.16;o.type=q[2];o.frequency.value=q[0];g.gain.setValueAtTime(.0001,t0);g.gain.exponentialRampToValueAtTime(.045,t0+.02);g.gain.exponentialRampToValueAtTime(.0001,t0+q[1]);o.connect(g).connect(c.destination);o.start(t0);o.stop(t0+q[1]+.03)})}
function legend(t){const p=t.pieces||{};return (p.ball?.name||'Golyó')+' · '+(p.brick?.name||'Tégla')+' · '+(p.wall?.name||'Fal')+' · '+(p.exit?.name||'Kijárat')+' · '+(t.abilities?.freeze?.name||'Freeze')}
function save(){localStorage.setItem(KEY,JSON.stringify([...enabled]));$('#count').textContent=enabled.size+' téma engedélyezve az Editor számára';render()}
function render(){gallery.innerHTML='';themes.forEach((m,i)=>{const t=docs.get(m.id),card=document.createElement('article');card.className='card'+(enabled.has(m.id)?' selected':'');card.innerHTML='<div class="card-head"><h2>'+m.name+'</h2><span class="badge">'+(enabled.has(m.id)?'Kiválasztva':'Nincs kiválasztva')+'</span></div><p>'+m.description+'</p>'+(m.showcase?'<div class="experimental showcase-badge">✦ MAXIMUM DETAIL SHOWCASE</div>':m.experimental?'<div class="experimental">Scene Theme · kísérleti</div>':'')+'<div class="scene"></div><div class="legend">'+legend(t)+'</div>'+(t.audio?'<button class="sound-demo" data-sound>🔊 Hangvilág próba · '+(t.audio.ambient?.name||t.audio.profile)+'</button>':'')+'<div class="card-actions"><button data-view>Megnyitás</button><button data-toggle>'+(enabled.has(m.id)?'Eltávolítás az Editorból':'Hozzáadás az Editorhoz')+'</button></div>';paint(card.querySelector('.scene'),t);card.querySelector('[data-sound]')?.addEventListener('click',()=>soundDemo(t));card.querySelector('[data-view]').onclick=()=>open(i);card.querySelector('[data-toggle]').onclick=()=>{enabled.has(m.id)?enabled.delete(m.id):enabled.add(m.id);save()};gallery.append(card)})}
function open(i){current=i;const m=themes[i],t=docs.get(m.id);$('#mName').textContent=m.name;$('#mDesc').textContent=m.description;paint($('#mScene'),t);$('#mLegend').textContent=legend(t);$('#toggle').textContent=enabled.has(m.id)?'✓ Kiválasztva – eltávolítás':'＋ Kerüljön a Scenario Editorba';$('#modal').hidden=false}
$('#close').onclick=()=>$('#modal').hidden=true;$('#prev').onclick=()=>open((current-1+themes.length)%themes.length);$('#next').onclick=()=>open((current+1)%themes.length);$('#toggle').onclick=()=>{const id=themes[current].id;enabled.has(id)?enabled.delete(id):enabled.add(id);localStorage.setItem(KEY,JSON.stringify([...enabled]));render();open(current)};$('#all').onclick=()=>{enabled=new Set(themes.map(x=>x.id));save()};$('#none').onclick=()=>{enabled=new Set();save()};$('#defaults').onclick=()=>{enabled=new Set(themes.map(x=>x.id));save()};
async function init(){const r=await fetch('content/themes/index.json',{cache:'no-cache'}),idx=await r.json();themes=idx.themes||[];await Promise.all(themes.filter(m=>m.previewCss).map(m=>new Promise(resolve=>{const link=document.createElement('link');link.rel='stylesheet';link.href=new URL(m.previewCss,new URL('content/themes/index.json',location.href)).href;link.onload=resolve;link.onerror=resolve;document.head.append(link)})));await Promise.all(themes.map(async m=>{const q=await fetch('content/themes/'+m.src,{cache:'no-cache'});docs.set(m.id,await q.json())}));try{const a=JSON.parse(localStorage.getItem(KEY)||'null');enabled=new Set(Array.isArray(a)?a:themes.map(x=>x.id))}catch(_){enabled=new Set(fallback)}save()}init().catch(e=>gallery.textContent='Theme Library betöltési hiba: '+e.message)})();